local_backend: true

backend:
  name: git-gateway
  branch: main
  cms_label_prefix: Otto

publish_mode: editorial_workflow
display_url_path: https://global.ijust.cc
site_url: https://global.ijust.cc

show_preview_links: true # default is true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "zh_Hans"

collections:
  - name: "post"
    label: "文章"
    folder: "src/content/post"
    create: true
    slug: "{{fields.slug}}"
    fields:
      # slug
      - { label: "URL", name: "slug", widget: "string", hint: "文章链接" }
      - { label: "标题", name: "title", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }
      - {
          label: "发布日期 Date",
          name: "publishDate",
          widget: "datetime",
          picker_utc: false,
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - { label: "关键词", name: "keywords", widget: "string", hint: "seo 要求" }
      - { label: "描述", name: "description", widget: "text", hint: "seo 要求" }

      # 排序权重 order number 0-99
      - {
          label: "排序权重",
          name: "order",
          widget: "number",
          default: 0,
          min: 0,
          max: 99,
          value_type: "int",
          hint: "数字越大越靠前，当置顶使用",
        }
      # tags list string
      - {
          label: "标签",
          name: "tags",
          widget: "list",
          field: { label: "标签", name: "tag", widget: "string" },
        }

      # 演示 select
      # - { label: '分类', name: 'category', widget: 'select', options: ['en', 'es'] }

  - name: "podcast"
    label: "播客"
    folder: "src/content/podcast"
    create: true
    slug: "{{fields.slug}}"

    fields:
      - { label: "URL", name: "slug", widget: "string", hint: "文章链接" }
      - { label: "标题", name: "title", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }
      - {
          label: "发布日期 Date",
          name: "publishDate",
          widget: "datetime",
          picker_utc: false,
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - { label: "关键词", name: "keywords", widget: "string", hint: "seo 要求" }
      - { label: "描述", name: "description", widget: "text", hint: "seo 要求" }

      # 排序权重 order number 0-99
      - {
          label: "排序权重",
          name: "order",
          widget: "number",
          default: 0,
          min: 0,
          max: 99,
          value_type: "int",
          hint: "数字越大越靠前，当置顶使用",
        }
      # tags list string
      - {
          label: "标签",
          name: "tags",
          widget: "list",
          field: { label: "标签", name: "tag", widget: "string" },
        }

      # 演示 select
      # - { label: '分类', name: 'category', widget: 'select', options: ['en', 'es'] }
